export const worldCurrencies = [
  { code: "LYD", name: "Libyan Dinar", symbol: "ل.د", rate: 0.00014 },
  { code: "USD", name: "US Dollar", symbol: "$", rate: 0.000066 },
  // { code: "LBP", name: "Lebanese Pound", symbol: "ل.ل", rate: 1 },
  // { code: "EUR", name: "Euro", symbol: "€", rate: 0.000061 },
  // { code: "GBP", name: "British Pound", symbol: "£", rate: 0.000052 },
  // { code: "JPY", name: "Japanese Yen", symbol: "¥", rate: 0.0099 },
  // { code: "AUD", name: "Australian Dollar", symbol: "A$", rate: 0.000099 },
  // { code: "CAD", name: "Canadian Dollar", symbol: "C$", rate: 0.000089 },
  // { code: "CHF", name: "Swiss Franc", symbol: "Fr", rate: 0.000059 },
  // { code: "CNY", name: "Chinese Yuan", symbol: "¥", rate: 0.00047 },
  // { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$", rate: 0.00051 },
  // { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$", rate: 0.00011 },
  // { code: "SEK", name: "Swedish Krona", symbol: "kr", rate: 0.00069 },
  // { code: "KRW", name: "South Korean Won", symbol: "₩", rate: 0.088 },
  // { code: "SGD", name: "Singapore Dollar", symbol: "S$", rate: 0.000088 },
  // { code: "NOK", name: "Norwegian Krone", symbol: "kr", rate: 0.00069 },
  // { code: "MXN", name: "Mexican Peso", symbol: "$", rate: 0.0011 },
  // { code: "INR", name: "Indian Rupee", symbol: "₹", rate: 0.0055 },
  // { code: "RUB", name: "Russian Ruble", symbol: "₽", rate: 0.0059 },
  // { code: "ZAR", name: "South African Rand", symbol: "R", rate: 0.0012 },
  // { code: "TRY", name: "Turkish Lira", symbol: "₺", rate: 0.0021 },
  // { code: "BRL", name: "Brazilian Real", symbol: "R$", rate: 0.00036 },
  // { code: "TWD", name: "Taiwan Dollar", symbol: "NT$", rate: 0.0021 },
  // { code: "DKK", name: "Danish Krone", symbol: "kr", rate: 0.00045 },
  // { code: "PLN", name: "Polish Zloty", symbol: "zł", rate: 0.00026 },
  // { code: "THB", name: "Thai Baht", symbol: "฿", rate: 0.0023 },
  // { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp", rate: 0.99 },
  // { code: "HUF", name: "Hungarian Forint", symbol: "Ft", rate: 0.024 },
  // { code: "CZK", name: "Czech Koruna", symbol: "Kč", rate: 0.0015 },
  // { code: "ILS", name: "Israeli Shekel", symbol: "₪", rate: 0.00024 },
  // { code: "CLP", name: "Chilean Peso", symbol: "$", rate: 0.06 },
  // { code: "PHP", name: "Philippine Peso", symbol: "₱", rate: 0.0037 },
  // { code: "AED", name: "UAE Dirham", symbol: "د.إ", rate: 0.00024 },
  // { code: "COP", name: "Colombian Peso", symbol: "$", rate: 0.26 },
  // { code: "SAR", name: "Saudi Riyal", symbol: "﷼", rate: 0.00025 },
  // { code: "MYR", name: "Malaysian Ringgit", symbol: "RM", rate: 0.0003 },
  // { code: "RON", name: "Romanian Leu", symbol: "lei", rate: 0.0003 },
  // { code: "ARS", name: "Argentine Peso", symbol: "$", rate: 0.059 },
  // { code: "BGN", name: "Bulgarian Lev", symbol: "лв", rate: 0.00012 },
  // { code: "PEN", name: "Peruvian Sol", symbol: "S/", rate: 0.00024 },
  // { code: "NGN", name: "Nigerian Naira", symbol: "₦", rate: 0.085 },
  // { code: "MAD", name: "Moroccan Dirham", symbol: "د.م.", rate: 0.00067 },
  // { code: "VND", name: "Vietnamese Dong", symbol: "₫", rate: 1.65 },
  // { code: "EGP", name: "Egyptian Pound", symbol: "E£", rate: 0.0021 },
  // { code: "KES", name: "Kenyan Shilling", symbol: "KSh", rate: 0.0085 },
  // { code: "PKR", name: "Pakistani Rupee", symbol: "₨", rate: 0.018 },
  // { code: "QAR", name: "Qatari Riyal", symbol: "﷼", rate: 0.00024 },
  // { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك", rate: 0.00002 },
  // { code: "JOD", name: "Jordanian Dinar", symbol: "JD", rate: 0.000047 },
  // { code: "BHD", name: "Bahraini Dinar", symbol: ".د.ب", rate: 0.000025 },
  // { code: "OMR", name: "Omani Rial", symbol: "﷼", rate: 0.000025 },
  // { code: "BTC", name: "Bitcoin", symbol: "₿", rate: 0.0000000012 },
  // { code: "ETH", name: "Ethereum", symbol: "Ξ", rate: 0.000000034 },
  // { code: "XAU", name: "Gold (troy ounce)", symbol: "XAU", rate: 0.0000000341 },
  // { code: "XAG", name: "Silver (troy ounce)", symbol: "XAG", rate: 0.00000284 },
];
